CURSO BANCO DE DADOS SQL - UDEMY

### AULA 8 SQL ###

# TABELA CLIENTE #

NOME CARACTER (30)
CPF NUMERICO (11)
EMAIL CARACTER (30)
TELEFONE CARACTER (30)
SEXO CARACTER (1)
ENDEREÇO CARACTER (100)

# ETAPAS INICIAIS #

# MODELAGEM CONCEITUAL - RASCUNHO #

# MODELAGEM LOGICA - PROGRAMAS COMO SUBLIME - NOTEPED++ #

# MODELAGEM FISICA - SCRIPT DO BANCO #


# CRIANDO BANCO DE DADOS #

CREATE DATABASE PROJETO;

# CONECTANDO AO BANCO #

USE PROJETO;

# CRIANDO A TABELA #

CREATE TABLE CLIENTE(
	NOME VARCHAR(30)
	SEXO CHAR(1)
	EMAIL VARCHAR(30)
	CPF INT(11)
	TELEFONE VARCHAR(30)
	ENDERECO VARCHAR(100)
	);
	
# VERIFICANDO AS TABELAS #
SHOW TABLES;

# DESCREVENDO TABELAS #
DESC CLIENTE;

### AULA 9 ###

# PARA CARACTER LITERAIS COMO ÁRVORE, JOÃO, MATEMÁTICA.
# USAR --> CHAR e VARCHAR
# CHAR > PREENCHER SEMPRE (10).
# VARCHAR > PREENCHER QT DE CARACTERC JOÃO(4)

# PARA CARACTER NÚMEROS --> INT e FLOT.
# FLOT USADO PARA NUMEROS REAIS EX: 1345,89 FLOAT (6,2)
# INT USADO PARA NUMEROS INTEIROS EX: 10 23 500.
# NUMEROS QUE Ñ NECESSITAM DE CÁLCULOS PODEM SER TIPADOS COMO VARCHAR!

# PARA FOTOS DOCUMENTOS --> BLOB.

# PARA TEXTO INTENSOS E GRANDES --> TEXT.

### AULA 11 ###

# MOSTRANDO AS TABELAS #
SHOW TABLES

# EXIBINDO A ESTRUTURA DE UMA TABELA #
DESC CLIENTE

# INSERINDO INFORMAÇÃO NAS COLUNAS #

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',983638273,'229233110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');


### FORMA 02 - COLOCANDO AS COLUNAS ###

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',30414212319);

# FORMA 03 - INSERT COMPACTO -  SOMENTE EM MYSQL #

INSERT INTO CLIENTE VALUES ('ANA','F',ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP),

						   

# AULA 13 COMANDO SELECT #




### AULA 13 -  COMANDO SELECT ###

SELECT NOW();

SELECT 'FELIPE MAPRA';

SELECT 'BANCO DE DADOS';

### ALIAS DE COLUNAS ###

SELECT 'RAFAEL MACEDO' AS O CARA;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

### APENAS PARA FINS ACADEMICOS ###

SELECT * FROM CLIENTES;



