
COMPRAR CURSO SQL PARA BIG DATA DA (DSA)

CURSO BANCO DE DADOS SQL

# CRIANDO BANCO DE DADOS #


Banco de Dados

Comandos no SQL 

1- Grupo.

DML > (Data Manipulation Language) (Desenvolvimento)

> SELECT: Pesquisa
> UPDATE: Atualização de Dados
> DELETE: Eliminação de Dados
> INSERT: Inserção de Dados


2- Grupo.

DDL (Data Definition Language) (Suporte)

> CREATE: Definição de um objeto (tabela, Índice)
> ALTER: Alteração de um objeto.
> DROP: Eliminação de um objeto.


3-Grupo.

DCL > (Data Control Language) (Suporte/Desenvolvimento)

> GRANT : Fornecer um privilégio
> REVOKE : Tirar um privilégio

---------------------------------------------------------





CREATE DATABASE PROJETO;

# CONECTANDO AO BANCO #

USE PROJETO;

# CRIANDO A TABELA #

CREATE TABLE CLIENTE(
	NOME VARCHAR(30)
	SEXO CHAR(1)
	EMAIL VARCHAR(30)
	CPF INT(11)
	TELEFONE VARCHAR(30)
	ENDERECO VARCHAR(100)
	);
	
# VERIFICANDO AS TABELAS #
	SHOW TABLES;

# DESCREVENDO TABELAS #
DESC CLIENTE;

### AULA 9 ###

	# PARA CARACTER LITERAIS COMO ÁRVORE, JOÃO, MATEMÁTICA.
# USAR --> CHAR e VARCHAR
# CHAR > PREENCHER SEMPRE (10).
# VARCHAR > PREENCHER QT DE CARACTERC JOÃO(4)

# PARA CARACTER NÚMEROS --> INT e FLOT.
# FLOT USADO PARA NUMEROS REAIS EX: 1345,89 FLOAT (6,2)
# INT USADO PARA NUMEROS INTEIROS EX: 10 23 500.
# NUMEROS QUE Ñ NECESSITAM DE CÁLCULOS PODEM SER TIPADOS COMO VARCHAR!

# PARA FOTOS DOCUMENTOS --> BLOB.

# PARA TEXTO INTENSOS E GRANDES --> TEXT.

### AULA 11 ###

# MOSTRANDO AS TABELAS #
SHOW TABLES

# EXIBINDO A ESTRUTURA DE UMA TABELA #
DESC CLIENTE

# INSERINDO INFORMAÇÃO NAS COLUNAS #

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',983638273,'229233110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');


### FORMA 02 - COLOCANDO AS COLUNAS ###

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',30414212319);

# FORMA 03 - INSERT COMPACTO -  SOMENTE EM MYSQL #

INSERT INTO CLIENTE VALUES ('ANA','F',ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP),

						   

# AULA 13 COMANDO SELECT #



### AULA 13 -  COMANDO SELECT ###


SELECT NOW(); # Serve para mostrar qualquer coisa # 

SELECT 'FELIPE MAPRA';

SELECT 'BANCO DE DADOS';

### ALIAS DE COLUNAS / são apelidos ###

SELECT 'RAFAEL MACEDO' AS O CARA;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT SEXO, EMAIL FROM CLIENTE;    */# A FORMA DE COLOCAR O SELECT MOSTRA A SEQUENCIA QUE TRAZ A CONSULTA #*/

### APENAS PARA FINS ACADEMICOS ###

SELECT * FROM CLIENTES;


*/# CONSULTA UTLIZANDO FILTRO WHERE */#

*/# ESSA FUNÇÃO ABAIXO VAI TRAZER APENAS INFORMAÇÃO MASCULINA DA TABELA */#

SELECT NOME, SEXO, FROM CLINTE
WHERE SEXO = 'M';

SELECT NOME, SEXO, FROM CLINTE
WHERE SEXO = 'F';

SELECT NOME, SEXO, FROM CLINTE
WHERE ENDERECO = 'RJ';

SHOW TABLES; Apenas no MYSQL traz qualquer coisa do banco #


## EXEMPLOS ##

''' ! Tipo	Explicação	Valores permitidos	Exemplo
BOOLEAN	Armazena um bit de informação, utilizado para verdadeiro ou falso.	Verdadeiro/falso	true/false
VARCHAR(n)	Uma string com tamanho máximo n	[0-9a-zA-Z]+{n}	"foo"
CHAR(n)	Uma string com tamanho fixo n	[0-9a-zA-Z]{n}	"foo"
SMALLINT	Número inteiro com 16 bits de precisão	\-?[0-9]+	584
INTEGER	Número inteiro com 32 bits de precisão	\-?[0-9]+	-8748
FLOAT	Número decimal	\-?[0-9]+[\.[0-9]+]?	48.96
NUMBER(n,[d])	Um número com n dígitos (e d dígitos decimais se mencionado)	\-?[0-9]+[\.[0-9]+]?	484.65
DATE	Uma data (Padrão americano)	[0-9][0-9][0-9][0-9]\-[0-1][0-9]\-[0-3][0-9]	2009-03-24
TIME	Um período de sessenta minutos; 1/24 de um dia	[0-2][0-9]\:[0-5][0-9]\:[0-5][0-9]	11:24:56
TIMESTAMP	Data e hora	[0-9]+	18648689595962
BLOB	Qualquer dado	Qualquer	'''



####    ####

SELECT COUNT * FROM CLIENTE;

SELECT COUNT * AS "QUANTIDADE" FROM CLIENTE;


#########  17.09.2019 #####

CREATE DATABASE ESTUDO;

USE ESTUDO;

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF VARCHAR(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
	CIDADE VARCHAR(30)
	ID VARCHAR(1000)
	);


INSERT INTO CLIENTE VALUES('RAFAEL','M','RAFAEL@GMAIL.COM',983638273,'229233110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ','RIO DE JANEIRO',1);

INSERT INTO CLIENTE VALUES('ARTHUR','M','ARTHUR@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ','RIO DE JANEIRO',2);

INSERT INTO CLIENTE VALUES('EVELYN','F',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG','MINAS GERAIS',3);

INSERT INTO CLIENTE VALUES('LUCIA','F',NULL,585755896,'58748895','OSCAR MARIA - BOM RETIRO - PATOS DE MINAS - SP','SÃO PAULO',4);

INSERT INTO CLIENTE VALUES('LUIS','M','LUIS@GMAIL.COM',685755896,'58748895','OSCAR SANTO - BOM RETIRO - CENTRO - SP','SÃO PAULO',5);

INSERT INTO CLIENTE VALUES('PEDRO','M','PEDRO@GMAIL.COM',785755896,'58748895','OSCAR FLEURY - BOM RETIRO - PERDIZES - SP','SÃO PAULO',6);

INSERT INTO CLIENTE VALUES('ADEMAR ','M','ADEMAR@GMAIL.COM',785755896,'58748895','ESTRADA CAPAO - VALE DO CAPAO - PALMEIRAS - BA','BAHIA',7);

INSERT INTO CLIENTE VALUES('PEDRO','M','PEDRO@GMAIL.COM',785755896,'58748895','OSCAR FLEURY - BOM RETIRO - PERDIZES - SP','SÃO PAULO',8);

INSERT INTO CLIENTE VALUES('LUIS CARLOS JUNIOR','M','PEDRO@GMAIL.COM',565755896,'58748895','BERNARDES MARCOLINO - VILA AURORA - ITAPEVI - SP','SÃO PAULO',9);

SELECT * FROM CLIENTE;

# CONTANDO QT DE LINHAS DA TABELA #
SELECT COUNT(*) FROM CLIENTE;

#QUANTIDADE DE REGISTROS DA TABELA#
SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TABELA"
FROM CLIENTE;

# APONTAR QUANTIDADE DE CADA SEXO TEM NA TABELA ##
SELECT SEXO, count(*) AS "QUANTIDADE"
FROM CLIENTE
GROUP BY SEXO;


# FUNÇÃO OR # MODO DE COMO CONTAR APENAS SEXO (F) NA TABELA  QUE MORA NO rIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'f'
OR ENDERECO = 'RIO DE JANEIRO'


# FUNÇÃO AND # QUAM TEM A MENOR CONDIÇÃO DE SER VERDADEIRO NA TABELA #
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE ENDERECO = 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG'
AND SEXO = 'F';


SELECT * FROM CLIENTE;


# TRAZER CAMPOS NULO NA TABELA #
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL = NULL;

# TRAZER CAMPOS É NULO NA TABELA #
SELECT NOME, SEXO, ENDERECO, EMAIL
FROM CLIENTE
WHERE EMAIL IS NULL;

# TRAZER CAMPOS NÃO NULO NA TABELA #
SELECT NOME, SEXO, ENDERECO, EMAIL
FROM CLIENTE
WHERE EMAIL IS NOT NULL;



CLAUSULA UPDATE

# CLAUSULA UPDATE PARA ATUALIZAR VALORES #

# MOSTRAR NA TABELA AS 2 COLUNAS NOME E EMAIL #
SELECT NOME, EMAIL
FROM CLIENTE;

# UTILIZAR O UPDATE SEMPRE ACOMPANHADO DA CLAUSULA WHERE #

UPDATE CLIENTE
SET EMAIL ='EVELYN@HOTMAIL.COM'
WHERE NOME ='EVELYN';

UPDATE CLIENTE
SET EMAIL ='LUCIA@GMAIL.COM'
WHERE NOME ='LUCIA';

###########################################


SELECT * FROM CLIENTE;

# INSERINDO COLUNA NA TABELA #
Alter table CLIENTE Add CIDADE VARCHAR(30);

ALTER TABLE CLIENTE ADD ID VARCHAR(1000);

# APAGAR COLUNA #
ALTER TABLE CLIENTE DROP COLUMN CIDADE;

# APAGAR LINHA DA TABELA #
DELETE FROM CLIENTE
WHERE NOME = 'PEDRO';

#### AULA 16 ####

** ENTRANDO COM MAIS TELEFONES **

# INSERINDO SEGUNDO TELEFONE NO REGIDTRO ##
UPDATE CLIENTE 
SET TELEFONE = '229233110 - 968894243'
WHERE NOME = 'RAFAEL'

SELECT * FROM CLIENTE;

# CONTANDO QT DE REGISDTRO POR CIDADE ##
SELECT CIDADE, COUNT(*) AS "QUANTIDADE"
FROM CLIENTE
GROUP BY CIDADE;

----------------------------------------

## 1 - FORMA NORMAL ##

/ 1 TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA > ELEMENTOS DO MESMO TIPO

/ 2 TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA > UM CAMPO DIVISIVEL 

/ 3 TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE INDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO.
 > É O QUE CHAMAMOS DE CHAVE PRIMÁRIA OU PRIMARY KEY*/

  / * PRIMEIRO ALGARISMO - OBRIGATORIEDADE
 0 - NÃO OBRIGATORIO
 1 - OBRIGATORIO

 / * SEGUNDO ALGARISMO - CARDINALIDADE
 1 - MAXIMO DE UM
 N - MAIS DE UM



  # MODELAGEM DO CLIENTE #

 CREATE DATABASE COMERCIO;

 USE COMERCIO;

 # ENTEDER COMO USAR VARIAVEL (ENUM) CAMPO SEXO - PARA FIXAR DOIS VALORES ###
  CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE, 
	CPF VARCHAR(15) UNIQUE,
	Sexo ENUM(1) NOT NULL
);
--------------------------------------

 # MODELAGEM DO CLIENTE #

CREATE DATABASE COMERCIO;

 USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE, 
	CPF VARCHAR(15) UNIQUE,
	Sexo ENUM('M','F') NOT NULL
);

create table TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL'),
	NUMERO VARCHAR(10),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/ * CHAVE ESTRANGEIRA - FK

É A CHAVE PRIMARIA DE UMA TABELA, QUE VAI ATÉ OUTRA TABELA FAZER REFERENCIA */

## APAGAR TABELA TELEFONE  ##
DROP TABLE TELEFONE;
ALTER TABLE TELEFONE DROP FOREIGN KEY ID_CLIENTE;
ALTER TABLE TELEFONE DROP INDEX ID_CLIENTE;


SELECT * FROM CLIENTE;

## INSERIRNDO INFORMAÇÕES NA TABELA CLIENTE ##
INSERT INTO CLIENTE VALUES(NULL,'RAFAEL','RAFAEL.MACEDO@BLUESHIFT.COM.BR',89011867090,'M');
INSERT INTO CLIENTE VALUES(NULL,'EVELYN','EVELYN.MACEDO@GMAIL.COM.BR',79011867090,'F');
INSERT INTO CLIENTE VALUES(NULL,'ARTHUR','ARTHUR.MACEDO@GMAIL.COM.BR',69011867090,'M');
INSERT INTO CLIENTE VALUES(NULL,'LINA','LINA.MACEDO@GMAIL.COM.BR',59011867090,'F');
INSERT INTO CLIENTE VALUES(NULL,'ADEMAR','ADEMAR.MACEDO@GMAIL.COM.BR',49011867090,'M');
INSERT INTO CLIENTE VALUES(NULL,'JUNIOR','JUNIOR.MACEDO@GMAIL.COM.BR',39011867090,'M');
INSERT INTO CLIENTE VALUES(NULL,'FERNANDO','FERNANDO.MACEDO@GMAIL.COM.BR',29011867090,'M');
INSERT INTO CLIENTE VALUES(NULL,'URSULA','URSULA.MACEDO@GMAIL.COM.BR',19011867090,'F');
INSERT INTO CLIENTE VALUES(NULL,'LUIS','LUIS.MACEDO@GMAIL.COM.BR',13011867090,'M');
INSERT INTO CLIENTE VALUES(NULL,'LUCIA','LUCIA.MACEDO@GMAIL.COM.BR',14011867090,'F');
INSERT INTO CLIENTE VALUES(NULL,'FERNANDO',NULL,15011867099,'M');


DESC ENDERECO;

## INSERIRNDO INFORMAÇÕES NA TABELA ENDEREÇO ##
INSERT INTO ENDERECO VALUES(NULL,'RUA A','CENTRO','BELO HORIZONTE','MG',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','CENTRO','BELO HORIZONTE','MG',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA C','CENTRO','BELO HORIZONTE','MG',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA D','CENTRO','BELO HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA E','CENTRO','BELO HORIZONTE','MG',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA F','CENTRO','BELO HORIZONTE','MG',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA G','CENTRO','BELO HORIZONTE','MG',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA H','CENTRO','BELO HORIZONTE','MG',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA I','CENTRO','BELO HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA J','CENTRO','BELO HORIZONTE','MG',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA L','CENTRO','BELO HORIZONTE','MG',11);

SELECT * FROM TELEFONE;
## INSERINDO INFORMAÇÕES NA TABELA TELEFONE ##
INSERT INTO TELEFONE VALUES(NULL,'CEL','968894250',4);
INSERT INTO TELEFONE VALUES(NULL,'COM','41415500',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','21001010',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','968894244',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','968894243',8);
INSERT INTO TELEFONE VALUES(NULL,'CEL','968894245',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','32147890',10);
INSERT INTO TELEFONE VALUES(NULL,'CEL','968894246',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','968894243',4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','968894247',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','21134567',6);


## CONCEITO ##

## SELEÇÃO - PROJEÇÃO - JUNÇÃO ##

## PROJEÇÃO TUDO QUE QUEREMOS MOSTRAR NA TELA ##
# PROJETANDO UMA TABELA #
SELECT NOW() AS "DATA"; 

SELECT NOME, NOW() AS "DATA" / > ISSO É UMA PROJEÇÃO
FROM CLIENTE;

### SELEÇÃO TEORIA DOS CONJUNTOS ###

SELECT NOME, SEXO
FROM CLIENTE;

SELECT NOME, SEXO
FROM CLIENTE
WHERE SEXO = 'M';  /* SELECAO */

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 5; /* SELECAO */

---------------------------------------

Banco de Dados

Comandos no SQL 

1- Grupo.

DML > (Data Manipulation Language) (Desenvolvimento)

> SELECT: Pesquisa
> UPDATE: Atualização de Dados
> DELETE: Eliminação de Dados
> INSERT: Inserção de Dados


2- Grupo.

DDL (Data Definition Language) (Suporte)

> CREATE: Definição de um objeto (tabela, Índice)
> ALTER: Alteração de um objeto.
> DROP: Eliminação de um objeto.


3-Grupo.

DCL > (Data Control Language) (Suporte/Desenvolvimento)

> GRANT : Fornecer um privilégio
> REVOKE : Tirar um privilégio

================================================================







