# PROJETO 2 #

CREATE TABLE ods1.pedidos00 (
  `freedom_order_sr_order` text DEFAULT NULL,
  `freedom_order_sr_payments` text DEFAULT NULL,
  `freedom_order_sr_shipping` text DEFAULT NULL,
  `freedom_order_sr_customer` text DEFAULT NULL,
  `freedom_order_sr_sku` text DEFAULT NULL,
  `freedom_order_catalog` text DEFAULT NULL,
  `freedom_order_storecode` text DEFAULT NULL,
  `freedom_order_saledate` text DEFAULT NULL,
  `freedom_order_saleschannel` text DEFAULT NULL,
  `freedom_order_amount` text DEFAULT NULL,
  `freedom_order_subtotal` text DEFAULT NULL,
  `freedom_order_id_code` text DEFAULT NULL,
  `freedom_order_id_origin` text DEFAULT NULL,
  `freedom_order_id_country` text DEFAULT NULL,
  `freedom_order_customer_externalcode` text DEFAULT NULL,
  `freedom_order_customer_name` text DEFAULT NULL,
  `freedom_order_customer_email` text DEFAULT NULL,
  `freedom_order_customer_cpfcnpj` text DEFAULT NULL,
  `freedom_order_customer_inscricaoestadual` text DEFAULT NULL,
  `freedom_order_customer_birthdate` text DEFAULT NULL,
  `freedom_order_customer_createdate` text DEFAULT NULL,
  `freedom_order_customer_gender` text DEFAULT NULL,
  `freedom_order_customer_persontype` text DEFAULT NULL,
  `freedom_order_customer_phonenumber` text DEFAULT NULL,
  `freedom_order_customer_phoneddd` text DEFAULT NULL,
  `freedom_order_customer_mobilenumber` text DEFAULT NULL,
  `freedom_order_customer_mobileddd` text DEFAULT NULL,
  `freedom_order_customer_score` text DEFAULT NULL,
  `freedom_order_customer_address_country` text DEFAULT NULL,
  `freedom_order_customer_address_state` text DEFAULT NULL,
  `freedom_order_customer_address_statecode` text DEFAULT NULL,
  `freedom_order_customer_address_city` text DEFAULT NULL,
  `freedom_order_customer_address_street` text DEFAULT NULL,
  `freedom_order_customer_address_number` text DEFAULT NULL,
  `freedom_order_customer_address_district` text DEFAULT NULL,
  `freedom_order_customer_address_postalcode` text DEFAULT NULL,
  `freedom_order_customer_address_referencepoint` text DEFAULT NULL,
  `freedom_order_customer_address_description` text DEFAULT NULL,
  `freedom_order_customer_address_businessaddress` text DEFAULT NULL,
  `freedom_order_payments_cardholder` text DEFAULT NULL,
  `freedom_order_payments_expirationmonth` text DEFAULT NULL,
  `freedom_order_payments_expirationyear` text DEFAULT NULL,
  `freedom_order_payments_securitycode` text DEFAULT NULL,
  `freedom_order_payments_cardbrand` text DEFAULT NULL,
  `freedom_order_payments_installmentsnumber` text DEFAULT NULL,
  `freedom_order_payments_value` text DEFAULT NULL,
  `freedom_order_payments_optin` text DEFAULT NULL,
  `freedom_order_payments_externalcode` text DEFAULT NULL,
  `freedom_order_payments_paymentdate` text DEFAULT NULL,
  `freedom_order_payments_deliveryid` text DEFAULT NULL,
  `freedom_order_payments_typepayment` text DEFAULT NULL,
  `freedom_order_shippings_deliveryid` text DEFAULT NULL,
  `freedom_order_shippings_servicedelivery` text DEFAULT NULL,
  `freedom_order_shippings_deadlineindays` text DEFAULT NULL,
  `freedom_order_shippings_expecteddeliverydate` text DEFAULT NULL,
  `freedom_order_shippings_freight` text DEFAULT NULL,
  `freedom_order_shippings_canceledpayment` text DEFAULT NULL,
  `freedom_order_shippings_status` text DEFAULT NULL,
  `freedom_order_shippings_laststatusdate` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_date` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_username` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_status` text DEFAULT NULL,
  `freedom_order_shippings_address_country` text DEFAULT NULL,
  `freedom_order_shippings_address_state` text DEFAULT NULL,
  `freedom_order_shippings_address_statecode` text DEFAULT NULL,
  `freedom_order_shippings_address_city` text DEFAULT NULL,
  `freedom_order_shippings_address_street` text DEFAULT NULL,
  `freedom_order_shippings_address_number` text DEFAULT NULL,
  `freedom_order_shippings_address_district` text DEFAULT NULL,
  `freedom_order_shippings_address_postalcode` text DEFAULT NULL,
  `freedom_order_shippings_address_referencepoint` text DEFAULT NULL,
  `freedom_order_shippings_address_description` text DEFAULT NULL,
  `freedom_order_shippings_address_businessaddress` text DEFAULT NULL,
  `freedom_order_shippings_recipient_name` text DEFAULT NULL,
  `freedom_order_shippings_recipient_cpfcnpj` text DEFAULT NULL,
  `freedom_order_shippings_recipient_birthdate` text DEFAULT NULL,
  `freedom_order_shippings_recipient_gender` text DEFAULT NULL,
  `freedom_order_shippings_recipient_persontype` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phonenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phoneddd` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobilenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobileddd` text DEFAULT NULL,
  `freedom_order_shippings_products_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_products_sku` text DEFAULT NULL,
  `freedom_order_shippings_products_unitprice` text DEFAULT NULL,
  `freedom_order_shippings_products_unitdiscount` text DEFAULT NULL,
  `freedom_order_shippings_products_quantity` text DEFAULT NULL,
  `freedom_order_shippings_products_productname` text DEFAULT NULL,
  `freedom_order_shippings_products_freebie` text DEFAULT NULL,
  `freedom_order_shippings_products_netprice` text DEFAULT NULL,
  `freedom_order_shippings_carrier_id` text DEFAULT NULL,
  `freedom_order_shippings_carrier_tradingname` text DEFAULT NULL,
  `freedom_order_timestamp` text DEFAULT NULL,
  `freedom_order_shippings_sellerid` text DEFAULT NULL,
  `freedom_order_shippings_agreedate` text DEFAULT NULL,
  `freedom_order_device` text DEFAULT NULL,
  `freedom_order_utm_key` text DEFAULT NULL,
  `freedom_order_utm_value` text DEFAULT NULL,
  `freedom_order_unique_id` text DEFAULT NULL,
  `freedom_order_utm_key_id` text DEFAULT NULL,
  `freedom_order_date_publish_kafka` text DEFAULT NULL,
  `freedom_order_nm_country` text DEFAULT NULL,
  `freedom_order_date_load` text DEFAULT NULL,
  `freedom_order_hour_load` text DEFAULT NULL,
  `freedom_order_minute_load` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

select * from ods1.pedidos00;

create database stage1;
use stage1;
CREATE TABLE stage1.pedidos00cleansing (
  `freedom_order_sr_order` text DEFAULT NULL,
  `freedom_order_sr_payments` text DEFAULT NULL,
  `freedom_order_sr_shipping` text DEFAULT NULL,
  `freedom_order_sr_customer` text DEFAULT NULL,
  `freedom_order_sr_sku` text DEFAULT NULL,
  `freedom_order_catalog` text DEFAULT NULL,
  `freedom_order_storecode` text DEFAULT NULL,
  `freedom_order_saledate` text DEFAULT NULL,
  `freedom_order_saleschannel` text DEFAULT NULL,
  `freedom_order_amount` text DEFAULT NULL,
  `freedom_order_subtotal` text DEFAULT NULL,
  `freedom_order_id_code` text DEFAULT NULL,
  `freedom_order_id_origin` text DEFAULT NULL,
  `freedom_order_id_country` text DEFAULT NULL,
  `freedom_order_customer_externalcode` text DEFAULT NULL,
  `freedom_order_customer_name` text DEFAULT NULL,
  `freedom_order_customer_email` text DEFAULT NULL,
  `freedom_order_customer_cpfcnpj` text DEFAULT NULL,
  `freedom_order_customer_inscricaoestadual` text DEFAULT NULL,
  `freedom_order_customer_birthdate` text DEFAULT NULL,
  `freedom_order_customer_createdate` text DEFAULT NULL,
  `freedom_order_customer_gender` text DEFAULT NULL,
  `freedom_order_customer_persontype` text DEFAULT NULL,
  `freedom_order_customer_phonenumber` text DEFAULT NULL,
  `freedom_order_customer_phoneddd` text DEFAULT NULL,
  `freedom_order_customer_mobilenumber` text DEFAULT NULL,
  `freedom_order_customer_mobileddd` text DEFAULT NULL,
  `freedom_order_customer_score` text DEFAULT NULL,
  `freedom_order_customer_address_country` text DEFAULT NULL,
  `freedom_order_customer_address_state` text DEFAULT NULL,
  `freedom_order_customer_address_statecode` text DEFAULT NULL,
  `freedom_order_customer_address_city` text DEFAULT NULL,
  `freedom_order_customer_address_street` text DEFAULT NULL,
  `freedom_order_customer_address_number` text DEFAULT NULL,
  `freedom_order_customer_address_district` text DEFAULT NULL,
  `freedom_order_customer_address_postalcode` text DEFAULT NULL,
  `freedom_order_customer_address_referencepoint` text DEFAULT NULL,
  `freedom_order_customer_address_description` text DEFAULT NULL,
  `freedom_order_customer_address_businessaddress` text DEFAULT NULL,
  `freedom_order_payments_cardholder` text DEFAULT NULL,
  `freedom_order_payments_expirationmonth` text DEFAULT NULL,
  `freedom_order_payments_expirationyear` text DEFAULT NULL,
  `freedom_order_payments_securitycode` text DEFAULT NULL,
  `freedom_order_payments_cardbrand` text DEFAULT NULL,
  `freedom_order_payments_installmentsnumber` text DEFAULT NULL,
  `freedom_order_payments_value` text DEFAULT NULL,
  `freedom_order_payments_optin` text DEFAULT NULL,
  `freedom_order_payments_externalcode` text DEFAULT NULL,
  `freedom_order_payments_paymentdate` text DEFAULT NULL,
  `freedom_order_payments_deliveryid` text DEFAULT NULL,
  `freedom_order_payments_typepayment` text DEFAULT NULL,
  `freedom_order_shippings_deliveryid` text DEFAULT NULL,
  `freedom_order_shippings_servicedelivery` text DEFAULT NULL,
  `freedom_order_shippings_deadlineindays` text DEFAULT NULL,
  `freedom_order_shippings_expecteddeliverydate` text DEFAULT NULL,
  `freedom_order_shippings_freight` text DEFAULT NULL,
  `freedom_order_shippings_canceledpayment` text DEFAULT NULL,
  `freedom_order_shippings_status` text DEFAULT NULL,
  `freedom_order_shippings_laststatusdate` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_date` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_username` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_status` text DEFAULT NULL,
  `freedom_order_shippings_address_country` text DEFAULT NULL,
  `freedom_order_shippings_address_state` text DEFAULT NULL,
  `freedom_order_shippings_address_statecode` text DEFAULT NULL,
  `freedom_order_shippings_address_city` text DEFAULT NULL,
  `freedom_order_shippings_address_street` text DEFAULT NULL,
  `freedom_order_shippings_address_number` text DEFAULT NULL,
  `freedom_order_shippings_address_district` text DEFAULT NULL,
  `freedom_order_shippings_address_postalcode` text DEFAULT NULL,
  `freedom_order_shippings_address_referencepoint` text DEFAULT NULL,
  `freedom_order_shippings_address_description` text DEFAULT NULL,
  `freedom_order_shippings_address_businessaddress` text DEFAULT NULL,
  `freedom_order_shippings_recipient_name` text DEFAULT NULL,
  `freedom_order_shippings_recipient_cpfcnpj` text DEFAULT NULL,
  `freedom_order_shippings_recipient_birthdate` text DEFAULT NULL,
  `freedom_order_shippings_recipient_gender` text DEFAULT NULL,
  `freedom_order_shippings_recipient_persontype` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phonenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phoneddd` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobilenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobileddd` text DEFAULT NULL,
  `freedom_order_shippings_products_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_products_sku` text DEFAULT NULL,
  `freedom_order_shippings_products_unitprice` text DEFAULT NULL,
  `freedom_order_shippings_products_unitdiscount` text DEFAULT NULL,
  `freedom_order_shippings_products_quantity` text DEFAULT NULL,
  `freedom_order_shippings_products_productname` text DEFAULT NULL,
  `freedom_order_shippings_products_freebie` text DEFAULT NULL,
  `freedom_order_shippings_products_netprice` text DEFAULT NULL,
  `freedom_order_shippings_carrier_id` text DEFAULT NULL,
  `freedom_order_shippings_carrier_tradingname` text DEFAULT NULL,
  `freedom_order_timestamp` text DEFAULT NULL,
  `freedom_order_shippings_sellerid` text DEFAULT NULL,
  `freedom_order_shippings_agreedate` text DEFAULT NULL,
  `freedom_order_device` text DEFAULT NULL,
  `freedom_order_utm_key` text DEFAULT NULL,
  `freedom_order_utm_value` text DEFAULT NULL,
  `freedom_order_unique_id` text DEFAULT NULL,
  `freedom_order_utm_key_id` text DEFAULT NULL,
  `freedom_order_date_publish_kafka` text DEFAULT NULL,
  `freedom_order_nm_country` text DEFAULT NULL,
  `freedom_order_date_load` text DEFAULT NULL,
  `freedom_order_hour_load` text DEFAULT NULL,
  `freedom_order_minute_load` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

select * from stage1.pedidos00cleansing;

CREATE TABLE stage1.dimensao (
  freedom_order_sr_order TEXT DEFAULT NULL,
  freedom_order_sr_payments TEXT DEFAULT NULL,
  freedom_order_sr_shipping TEXT DEFAULT NULL,
  freedom_order_sr_customer TEXT DEFAULT NULL, 
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;

SET GLOBAL time_zone = '+8:00'; 
drop table ods1.pedidos01;

CREATE TABLE ods1.pedidos01 (
  `freedom_order_sr_order` text DEFAULT NULL,
  `freedom_order_sr_payments` text DEFAULT NULL,
  `freedom_order_sr_shipping` text DEFAULT NULL,
  `freedom_order_sr_customer` text DEFAULT NULL,
  `freedom_order_sr_sku` text DEFAULT NULL,
  `freedom_order_catalog` text DEFAULT NULL,
  `freedom_order_storecode` text DEFAULT NULL,
  `freedom_order_saledate` text DEFAULT NULL,
  `freedom_order_saleschannel` text DEFAULT NULL,
  `freedom_order_amount` text DEFAULT NULL,
  `freedom_order_subtotal` text DEFAULT NULL,
  `freedom_order_id_code` text DEFAULT NULL,
  `freedom_order_id_origin` text DEFAULT NULL,
  `freedom_order_id_country` text DEFAULT NULL,
  `freedom_order_customer_externalcode` text DEFAULT NULL,
  `freedom_order_customer_name` text DEFAULT NULL,
  `freedom_order_customer_email` text DEFAULT NULL,
  `freedom_order_customer_cpfcnpj` text DEFAULT NULL,
  `freedom_order_customer_inscricaoestadual` text DEFAULT NULL,
  `freedom_order_customer_birthdate` text DEFAULT NULL,
  `freedom_order_customer_createdate` text DEFAULT NULL,
  `freedom_order_customer_gender` text DEFAULT NULL,
  `freedom_order_customer_persontype` text DEFAULT NULL,
  `freedom_order_customer_phonenumber` text DEFAULT NULL,
  `freedom_order_customer_phoneddd` text DEFAULT NULL,
  `freedom_order_customer_mobilenumber` text DEFAULT NULL,
  `freedom_order_customer_mobileddd` text DEFAULT NULL,
  `freedom_order_customer_score` text DEFAULT NULL,
  `freedom_order_customer_address_country` text DEFAULT NULL,
  `freedom_order_customer_address_state` text DEFAULT NULL,
  `freedom_order_customer_address_statecode` text DEFAULT NULL,
  `freedom_order_customer_address_city` text DEFAULT NULL,
  `freedom_order_customer_address_street` text DEFAULT NULL,
  `freedom_order_customer_address_number` text DEFAULT NULL,
  `freedom_order_customer_address_district` text DEFAULT NULL,
  `freedom_order_customer_address_postalcode` text DEFAULT NULL,
  `freedom_order_customer_address_referencepoint` text DEFAULT NULL,
  `freedom_order_customer_address_description` text DEFAULT NULL,
  `freedom_order_customer_address_businessaddress` text DEFAULT NULL,
  `freedom_order_payments_cardholder` text DEFAULT NULL,
  `freedom_order_payments_expirationmonth` text DEFAULT NULL,
  `freedom_order_payments_expirationyear` text DEFAULT NULL,
  `freedom_order_payments_securitycode` text DEFAULT NULL,
  `freedom_order_payments_cardbrand` text DEFAULT NULL,
  `freedom_order_payments_installmentsnumber` text DEFAULT NULL,
  `freedom_order_payments_value` text DEFAULT NULL,
  `freedom_order_payments_optin` text DEFAULT NULL,
  `freedom_order_payments_externalcode` text DEFAULT NULL,
  `freedom_order_payments_paymentdate` text DEFAULT NULL,
  `freedom_order_payments_deliveryid` text DEFAULT NULL,
  `freedom_order_payments_typepayment` text DEFAULT NULL,
  `freedom_order_shippings_deliveryid` text DEFAULT NULL,
  `freedom_order_shippings_servicedelivery` text DEFAULT NULL,
  `freedom_order_shippings_deadlineindays` text DEFAULT NULL,
  `freedom_order_shippings_expecteddeliverydate` text DEFAULT NULL,
  `freedom_order_shippings_freight` text DEFAULT NULL,
  `freedom_order_shippings_canceledpayment` text DEFAULT NULL,
  `freedom_order_shippings_status` text DEFAULT NULL,
  `freedom_order_shippings_laststatusdate` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_date` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_username` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_status` text DEFAULT NULL,
  `freedom_order_shippings_address_country` text DEFAULT NULL,
  `freedom_order_shippings_address_state` text DEFAULT NULL,
  `freedom_order_shippings_address_statecode` text DEFAULT NULL,
  `freedom_order_shippings_address_city` text DEFAULT NULL,
  `freedom_order_shippings_address_street` text DEFAULT NULL,
  `freedom_order_shippings_address_number` text DEFAULT NULL,
  `freedom_order_shippings_address_district` text DEFAULT NULL,
  `freedom_order_shippings_address_postalcode` text DEFAULT NULL,
  `freedom_order_shippings_address_referencepoint` text DEFAULT NULL,
  `freedom_order_shippings_address_description` text DEFAULT NULL,
  `freedom_order_shippings_address_businessaddress` text DEFAULT NULL,
  `freedom_order_shippings_recipient_name` text DEFAULT NULL,
  `freedom_order_shippings_recipient_cpfcnpj` text DEFAULT NULL,
  `freedom_order_shippings_recipient_birthdate` text DEFAULT NULL,
  `freedom_order_shippings_recipient_gender` text DEFAULT NULL,
  `freedom_order_shippings_recipient_persontype` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phonenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phoneddd` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobilenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobileddd` text DEFAULT NULL,
  `freedom_order_shippings_products_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_products_sku` text DEFAULT NULL,
  `freedom_order_shippings_products_unitprice` text DEFAULT NULL,
  `freedom_order_shippings_products_unitdiscount` text DEFAULT NULL,
  `freedom_order_shippings_products_quantity` text DEFAULT NULL,
  `freedom_order_shippings_products_productname` text DEFAULT NULL,
  `freedom_order_shippings_products_freebie` text DEFAULT NULL,
  `freedom_order_shippings_products_netprice` text DEFAULT NULL,
  `freedom_order_shippings_carrier_id` text DEFAULT NULL,
  `freedom_order_shippings_carrier_tradingname` text DEFAULT NULL,
  `freedom_order_timestamp` text DEFAULT NULL,
  `freedom_order_shippings_sellerid` text DEFAULT NULL,
  `freedom_order_shippings_agreedate` text DEFAULT NULL,
  `freedom_order_device` text DEFAULT NULL,
  `freedom_order_utm_key` text DEFAULT NULL,
  `freedom_order_utm_value` text DEFAULT NULL,
  `freedom_order_unique_id` text DEFAULT NULL,
  `freedom_order_utm_key_id` text DEFAULT NULL,
  `freedom_order_date_publish_kafka` text DEFAULT NULL,
  `freedom_order_nm_country` text DEFAULT NULL,
  `freedom_order_date_load` text DEFAULT NULL,
  `freedom_order_hour_load` text DEFAULT NULL,
  `freedom_order_minute_load` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE ods1.pedidos04 (
  `freedom_order_sr_order` text DEFAULT NULL,
  `freedom_order_sr_payments` text DEFAULT NULL,
  `freedom_order_sr_shipping` text DEFAULT NULL,
  `freedom_order_sr_customer` text DEFAULT NULL,
  `freedom_order_sr_sku` text DEFAULT NULL,
  `freedom_order_catalog` text DEFAULT NULL,
  `freedom_order_storecode` text DEFAULT NULL,
  `freedom_order_saledate` text DEFAULT NULL,
  `freedom_order_saleschannel` text DEFAULT NULL,
  `freedom_order_amount` text DEFAULT NULL,
  `freedom_order_subtotal` text DEFAULT NULL,
  `freedom_order_id_code` text DEFAULT NULL,
  `freedom_order_id_origin` text DEFAULT NULL,
  `freedom_order_id_country` text DEFAULT NULL,
  `freedom_order_customer_externalcode` text DEFAULT NULL,
  `freedom_order_customer_name` text DEFAULT NULL,
  `freedom_order_customer_email` text DEFAULT NULL,
  `freedom_order_customer_cpfcnpj` text DEFAULT NULL,
  `freedom_order_customer_inscricaoestadual` text DEFAULT NULL,
  `freedom_order_customer_birthdate` text DEFAULT NULL,
  `freedom_order_customer_createdate` text DEFAULT NULL,
  `freedom_order_customer_gender` text DEFAULT NULL,
  `freedom_order_customer_persontype` text DEFAULT NULL,
  `freedom_order_customer_phonenumber` text DEFAULT NULL,
  `freedom_order_customer_phoneddd` text DEFAULT NULL,
  `freedom_order_customer_mobilenumber` text DEFAULT NULL,
  `freedom_order_customer_mobileddd` text DEFAULT NULL,
  `freedom_order_customer_score` text DEFAULT NULL,
  `freedom_order_customer_address_country` text DEFAULT NULL,
  `freedom_order_customer_address_state` text DEFAULT NULL,
  `freedom_order_customer_address_statecode` text DEFAULT NULL,
  `freedom_order_customer_address_city` text DEFAULT NULL,
  `freedom_order_customer_address_street` text DEFAULT NULL,
  `freedom_order_customer_address_number` text DEFAULT NULL,
  `freedom_order_customer_address_district` text DEFAULT NULL,
  `freedom_order_customer_address_postalcode` text DEFAULT NULL,
  `freedom_order_customer_address_referencepoint` text DEFAULT NULL,
  `freedom_order_customer_address_description` text DEFAULT NULL,
  `freedom_order_customer_address_businessaddress` text DEFAULT NULL,
  `freedom_order_payments_cardholder` text DEFAULT NULL,
  `freedom_order_payments_expirationmonth` text DEFAULT NULL,
  `freedom_order_payments_expirationyear` text DEFAULT NULL,
  `freedom_order_payments_securitycode` text DEFAULT NULL,
  `freedom_order_payments_cardbrand` text DEFAULT NULL,
  `freedom_order_payments_installmentsnumber` text DEFAULT NULL,
  `freedom_order_payments_value` text DEFAULT NULL,
  `freedom_order_payments_optin` text DEFAULT NULL,
  `freedom_order_payments_externalcode` text DEFAULT NULL,
  `freedom_order_payments_paymentdate` text DEFAULT NULL,
  `freedom_order_payments_deliveryid` text DEFAULT NULL,
  `freedom_order_payments_typepayment` text DEFAULT NULL,
  `freedom_order_shippings_deliveryid` text DEFAULT NULL,
  `freedom_order_shippings_servicedelivery` text DEFAULT NULL,
  `freedom_order_shippings_deadlineindays` text DEFAULT NULL,
  `freedom_order_shippings_expecteddeliverydate` text DEFAULT NULL,
  `freedom_order_shippings_freight` text DEFAULT NULL,
  `freedom_order_shippings_canceledpayment` text DEFAULT NULL,
  `freedom_order_shippings_status` text DEFAULT NULL,
  `freedom_order_shippings_laststatusdate` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_date` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_username` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_status` text DEFAULT NULL,
  `freedom_order_shippings_address_country` text DEFAULT NULL,
  `freedom_order_shippings_address_state` text DEFAULT NULL,
  `freedom_order_shippings_address_statecode` text DEFAULT NULL,
  `freedom_order_shippings_address_city` text DEFAULT NULL,
  `freedom_order_shippings_address_street` text DEFAULT NULL,
  `freedom_order_shippings_address_number` text DEFAULT NULL,
  `freedom_order_shippings_address_district` text DEFAULT NULL,
  `freedom_order_shippings_address_postalcode` text DEFAULT NULL,
  `freedom_order_shippings_address_referencepoint` text DEFAULT NULL,
  `freedom_order_shippings_address_description` text DEFAULT NULL,
  `freedom_order_shippings_address_businessaddress` text DEFAULT NULL,
  `freedom_order_shippings_recipient_name` text DEFAULT NULL,
  `freedom_order_shippings_recipient_cpfcnpj` text DEFAULT NULL,
  `freedom_order_shippings_recipient_birthdate` text DEFAULT NULL,
  `freedom_order_shippings_recipient_gender` text DEFAULT NULL,
  `freedom_order_shippings_recipient_persontype` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phonenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phoneddd` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobilenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobileddd` text DEFAULT NULL,
  `freedom_order_shippings_products_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_products_sku` text DEFAULT NULL,
  `freedom_order_shippings_products_unitprice` text DEFAULT NULL,
  `freedom_order_shippings_products_unitdiscount` text DEFAULT NULL,
  `freedom_order_shippings_products_quantity` text DEFAULT NULL,
  `freedom_order_shippings_products_productname` text DEFAULT NULL,
  `freedom_order_shippings_products_freebie` text DEFAULT NULL,
  `freedom_order_shippings_products_netprice` text DEFAULT NULL,
  `freedom_order_shippings_carrier_id` text DEFAULT NULL,
  `freedom_order_shippings_carrier_tradingname` text DEFAULT NULL,
  `freedom_order_timestamp` text DEFAULT NULL,
  `freedom_order_shippings_sellerid` text DEFAULT NULL,
  `freedom_order_shippings_agreedate` text DEFAULT NULL,
  `freedom_order_device` text DEFAULT NULL,
  `freedom_order_utm_key` text DEFAULT NULL,
  `freedom_order_utm_value` text DEFAULT NULL,
  `freedom_order_unique_id` text DEFAULT NULL,
  `freedom_order_utm_key_id` text DEFAULT NULL,
  `freedom_order_date_publish_kafka` text DEFAULT NULL,
  `freedom_order_nm_country` text DEFAULT NULL,
  `freedom_order_date_load` text DEFAULT NULL,
  `freedom_order_hour_load` text DEFAULT NULL,
  `freedom_order_minute_load` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

use stage1;
CREATE TABLE stage1.pedidos01cleansing (
  `freedom_order_sr_order` text DEFAULT NULL,
  `freedom_order_sr_payments` text DEFAULT NULL,
  `freedom_order_sr_shipping` text DEFAULT NULL,
  `freedom_order_sr_customer` text DEFAULT NULL,
  `freedom_order_sr_sku` text DEFAULT NULL,
  `freedom_order_catalog` text DEFAULT NULL,
  `freedom_order_storecode` text DEFAULT NULL,
  `freedom_order_saledate` text DEFAULT NULL,
  `freedom_order_saleschannel` text DEFAULT NULL,
  `freedom_order_amount` text DEFAULT NULL,
  `freedom_order_subtotal` text DEFAULT NULL,
  `freedom_order_id_code` text DEFAULT NULL,
  `freedom_order_id_origin` text DEFAULT NULL,
  `freedom_order_id_country` text DEFAULT NULL,
  `freedom_order_customer_externalcode` text DEFAULT NULL,
  `freedom_order_customer_name` text DEFAULT NULL,
  `freedom_order_customer_email` text DEFAULT NULL,
  `freedom_order_customer_cpfcnpj` text DEFAULT NULL,
  `freedom_order_customer_inscricaoestadual` text DEFAULT NULL,
  `freedom_order_customer_birthdate` text DEFAULT NULL,
  `freedom_order_customer_createdate` text DEFAULT NULL,
  `freedom_order_customer_gender` text DEFAULT NULL,
  `freedom_order_customer_persontype` text DEFAULT NULL,
  `freedom_order_customer_phonenumber` text DEFAULT NULL,
  `freedom_order_customer_phoneddd` text DEFAULT NULL,
  `freedom_order_customer_mobilenumber` text DEFAULT NULL,
  `freedom_order_customer_mobileddd` text DEFAULT NULL,
  `freedom_order_customer_score` text DEFAULT NULL,
  `freedom_order_customer_address_country` text DEFAULT NULL,
  `freedom_order_customer_address_state` text DEFAULT NULL,
  `freedom_order_customer_address_statecode` text DEFAULT NULL,
  `freedom_order_customer_address_city` text DEFAULT NULL,
  `freedom_order_customer_address_street` text DEFAULT NULL,
  `freedom_order_customer_address_number` text DEFAULT NULL,
  `freedom_order_customer_address_district` text DEFAULT NULL,
  `freedom_order_customer_address_postalcode` text DEFAULT NULL,
  `freedom_order_customer_address_referencepoint` text DEFAULT NULL,
  `freedom_order_customer_address_description` text DEFAULT NULL,
  `freedom_order_customer_address_businessaddress` text DEFAULT NULL,
  `freedom_order_payments_cardholder` text DEFAULT NULL,
  `freedom_order_payments_expirationmonth` text DEFAULT NULL,
  `freedom_order_payments_expirationyear` text DEFAULT NULL,
  `freedom_order_payments_securitycode` text DEFAULT NULL,
  `freedom_order_payments_cardbrand` text DEFAULT NULL,
  `freedom_order_payments_installmentsnumber` text DEFAULT NULL,
  `freedom_order_payments_value` text DEFAULT NULL,
  `freedom_order_payments_optin` text DEFAULT NULL,
  `freedom_order_payments_externalcode` text DEFAULT NULL,
  `freedom_order_payments_paymentdate` text DEFAULT NULL,
  `freedom_order_payments_deliveryid` text DEFAULT NULL,
  `freedom_order_payments_typepayment` text DEFAULT NULL,
  `freedom_order_shippings_deliveryid` text DEFAULT NULL,
  `freedom_order_shippings_servicedelivery` text DEFAULT NULL,
  `freedom_order_shippings_deadlineindays` text DEFAULT NULL,
  `freedom_order_shippings_expecteddeliverydate` text DEFAULT NULL,
  `freedom_order_shippings_freight` text DEFAULT NULL,
  `freedom_order_shippings_canceledpayment` text DEFAULT NULL,
  `freedom_order_shippings_status` text DEFAULT NULL,
  `freedom_order_shippings_laststatusdate` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_date` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_username` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_status` text DEFAULT NULL,
  `freedom_order_shippings_address_country` text DEFAULT NULL,
  `freedom_order_shippings_address_state` text DEFAULT NULL,
  `freedom_order_shippings_address_statecode` text DEFAULT NULL,
  `freedom_order_shippings_address_city` text DEFAULT NULL,
  `freedom_order_shippings_address_street` text DEFAULT NULL,
  `freedom_order_shippings_address_number` text DEFAULT NULL,
  `freedom_order_shippings_address_district` text DEFAULT NULL,
  `freedom_order_shippings_address_postalcode` text DEFAULT NULL,
  `freedom_order_shippings_address_referencepoint` text DEFAULT NULL,
  `freedom_order_shippings_address_description` text DEFAULT NULL,
  `freedom_order_shippings_address_businessaddress` text DEFAULT NULL,
  `freedom_order_shippings_recipient_name` text DEFAULT NULL,
  `freedom_order_shippings_recipient_cpfcnpj` text DEFAULT NULL,
  `freedom_order_shippings_recipient_birthdate` text DEFAULT NULL,
  `freedom_order_shippings_recipient_gender` text DEFAULT NULL,
  `freedom_order_shippings_recipient_persontype` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phonenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phoneddd` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobilenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobileddd` text DEFAULT NULL,
  `freedom_order_shippings_products_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_products_sku` text DEFAULT NULL,
  `freedom_order_shippings_products_unitprice` text DEFAULT NULL,
  `freedom_order_shippings_products_unitdiscount` text DEFAULT NULL,
  `freedom_order_shippings_products_quantity` text DEFAULT NULL,
  `freedom_order_shippings_products_productname` text DEFAULT NULL,
  `freedom_order_shippings_products_freebie` text DEFAULT NULL,
  `freedom_order_shippings_products_netprice` text DEFAULT NULL,
  `freedom_order_shippings_carrier_id` text DEFAULT NULL,
  `freedom_order_shippings_carrier_tradingname` text DEFAULT NULL,
  `freedom_order_timestamp` text DEFAULT NULL,
  `freedom_order_shippings_sellerid` text DEFAULT NULL,
  `freedom_order_shippings_agreedate` text DEFAULT NULL,
  `freedom_order_device` text DEFAULT NULL,
  `freedom_order_utm_key` text DEFAULT NULL,
  `freedom_order_utm_value` text DEFAULT NULL,
  `freedom_order_unique_id` text DEFAULT NULL,
  `freedom_order_utm_key_id` text DEFAULT NULL,
  `freedom_order_date_publish_kafka` text DEFAULT NULL,
  `freedom_order_nm_country` text DEFAULT NULL,
  `freedom_order_date_load` text DEFAULT NULL,
  `freedom_order_hour_load` text DEFAULT NULL,
  `freedom_order_minute_load` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE stage1.pedidos04cleansing (
  `freedom_order_sr_order` text DEFAULT NULL,
  `freedom_order_sr_payments` text DEFAULT NULL,
  `freedom_order_sr_shipping` text DEFAULT NULL,
  `freedom_order_sr_customer` text DEFAULT NULL,
  `freedom_order_sr_sku` text DEFAULT NULL,
  `freedom_order_catalog` text DEFAULT NULL,
  `freedom_order_storecode` text DEFAULT NULL,
  `freedom_order_saledate` text DEFAULT NULL,
  `freedom_order_saleschannel` text DEFAULT NULL,
  `freedom_order_amount` text DEFAULT NULL,
  `freedom_order_subtotal` text DEFAULT NULL,
  `freedom_order_id_code` text DEFAULT NULL,
  `freedom_order_id_origin` text DEFAULT NULL,
  `freedom_order_id_country` text DEFAULT NULL,
  `freedom_order_customer_externalcode` text DEFAULT NULL,
  `freedom_order_customer_name` text DEFAULT NULL,
  `freedom_order_customer_email` text DEFAULT NULL,
  `freedom_order_customer_cpfcnpj` text DEFAULT NULL,
  `freedom_order_customer_inscricaoestadual` text DEFAULT NULL,
  `freedom_order_customer_birthdate` text DEFAULT NULL,
  `freedom_order_customer_createdate` text DEFAULT NULL,
  `freedom_order_customer_gender` text DEFAULT NULL,
  `freedom_order_customer_persontype` text DEFAULT NULL,
  `freedom_order_customer_phonenumber` text DEFAULT NULL,
  `freedom_order_customer_phoneddd` text DEFAULT NULL,
  `freedom_order_customer_mobilenumber` text DEFAULT NULL,
  `freedom_order_customer_mobileddd` text DEFAULT NULL,
  `freedom_order_customer_score` text DEFAULT NULL,
  `freedom_order_customer_address_country` text DEFAULT NULL,
  `freedom_order_customer_address_state` text DEFAULT NULL,
  `freedom_order_customer_address_statecode` text DEFAULT NULL,
  `freedom_order_customer_address_city` text DEFAULT NULL,
  `freedom_order_customer_address_street` text DEFAULT NULL,
  `freedom_order_customer_address_number` text DEFAULT NULL,
  `freedom_order_customer_address_district` text DEFAULT NULL,
  `freedom_order_customer_address_postalcode` text DEFAULT NULL,
  `freedom_order_customer_address_referencepoint` text DEFAULT NULL,
  `freedom_order_customer_address_description` text DEFAULT NULL,
  `freedom_order_customer_address_businessaddress` text DEFAULT NULL,
  `freedom_order_payments_cardholder` text DEFAULT NULL,
  `freedom_order_payments_expirationmonth` text DEFAULT NULL,
  `freedom_order_payments_expirationyear` text DEFAULT NULL,
  `freedom_order_payments_securitycode` text DEFAULT NULL,
  `freedom_order_payments_cardbrand` text DEFAULT NULL,
  `freedom_order_payments_installmentsnumber` text DEFAULT NULL,
  `freedom_order_payments_value` text DEFAULT NULL,
  `freedom_order_payments_optin` text DEFAULT NULL,
  `freedom_order_payments_externalcode` text DEFAULT NULL,
  `freedom_order_payments_paymentdate` text DEFAULT NULL,
  `freedom_order_payments_deliveryid` text DEFAULT NULL,
  `freedom_order_payments_typepayment` text DEFAULT NULL,
  `freedom_order_shippings_deliveryid` text DEFAULT NULL,
  `freedom_order_shippings_servicedelivery` text DEFAULT NULL,
  `freedom_order_shippings_deadlineindays` text DEFAULT NULL,
  `freedom_order_shippings_expecteddeliverydate` text DEFAULT NULL,
  `freedom_order_shippings_freight` text DEFAULT NULL,
  `freedom_order_shippings_canceledpayment` text DEFAULT NULL,
  `freedom_order_shippings_status` text DEFAULT NULL,
  `freedom_order_shippings_laststatusdate` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_date` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_username` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_status` text DEFAULT NULL,
  `freedom_order_shippings_address_country` text DEFAULT NULL,
  `freedom_order_shippings_address_state` text DEFAULT NULL,
  `freedom_order_shippings_address_statecode` text DEFAULT NULL,
  `freedom_order_shippings_address_city` text DEFAULT NULL,
  `freedom_order_shippings_address_street` text DEFAULT NULL,
  `freedom_order_shippings_address_number` text DEFAULT NULL,
  `freedom_order_shippings_address_district` text DEFAULT NULL,
  `freedom_order_shippings_address_postalcode` text DEFAULT NULL,
  `freedom_order_shippings_address_referencepoint` text DEFAULT NULL,
  `freedom_order_shippings_address_description` text DEFAULT NULL,
  `freedom_order_shippings_address_businessaddress` text DEFAULT NULL,
  `freedom_order_shippings_recipient_name` text DEFAULT NULL,
  `freedom_order_shippings_recipient_cpfcnpj` text DEFAULT NULL,
  `freedom_order_shippings_recipient_birthdate` text DEFAULT NULL,
  `freedom_order_shippings_recipient_gender` text DEFAULT NULL,
  `freedom_order_shippings_recipient_persontype` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phonenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phoneddd` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobilenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobileddd` text DEFAULT NULL,
  `freedom_order_shippings_products_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_products_sku` text DEFAULT NULL,
  `freedom_order_shippings_products_unitprice` text DEFAULT NULL,
  `freedom_order_shippings_products_unitdiscount` text DEFAULT NULL,
  `freedom_order_shippings_products_quantity` text DEFAULT NULL,
  `freedom_order_shippings_products_productname` text DEFAULT NULL,
  `freedom_order_shippings_products_freebie` text DEFAULT NULL,
  `freedom_order_shippings_products_netprice` text DEFAULT NULL,
  `freedom_order_shippings_carrier_id` text DEFAULT NULL,
  `freedom_order_shippings_carrier_tradingname` text DEFAULT NULL,
  `freedom_order_timestamp` text DEFAULT NULL,
  `freedom_order_shippings_sellerid` text DEFAULT NULL,
  `freedom_order_shippings_agreedate` text DEFAULT NULL,
  `freedom_order_device` text DEFAULT NULL,
  `freedom_order_utm_key` text DEFAULT NULL,
  `freedom_order_utm_value` text DEFAULT NULL,
  `freedom_order_unique_id` text DEFAULT NULL,
  `freedom_order_utm_key_id` text DEFAULT NULL,
  `freedom_order_date_publish_kafka` text DEFAULT NULL,
  `freedom_order_nm_country` text DEFAULT NULL,
  `freedom_order_date_load` text DEFAULT NULL,
  `freedom_order_hour_load` text DEFAULT NULL,
  `freedom_order_minute_load` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

use stage1;
select * from stage1.pedidos00cleansing;
select * from stage1.pedidos01cleansing;
select * from stage1.pedidos04cleansing;

use ods1;
select * from ods1.pedidos00;
select * from ods1.pedidos01;
select * from ods1.pedidos04;

SET GLOBAL time_zone = '+8:00'; 

create database ods3totalpedidos;

drop database ods2;

select * from ods3.totalpedidos;

select * from ods3.totalpedidos;

select
convert(freedom_order_sr_order, text) from ods3.totalpedidos;
use ods3;
Select cast(freedom_order_sr_order as text) from ods3.totalpedidos;


CREATE TABLE ods3.totalpedidos (
  `freedom_order_sr_order` text DEFAULT NULL,
  `freedom_order_sr_payments` text DEFAULT NULL,
  `freedom_order_sr_shipping` text DEFAULT NULL,
  `freedom_order_sr_customer` text DEFAULT NULL,
  `freedom_order_sr_sku` text DEFAULT NULL,
  `freedom_order_catalog` text DEFAULT NULL,
  `freedom_order_storecode` text DEFAULT NULL,
  `freedom_order_saledate` text DEFAULT NULL,
  `freedom_order_saleschannel` text DEFAULT NULL,
  `freedom_order_amount` text DEFAULT NULL,
  `freedom_order_subtotal` text DEFAULT NULL,
  `freedom_order_id_code` text DEFAULT NULL,
  `freedom_order_id_origin` text DEFAULT NULL,
  `freedom_order_id_country` text DEFAULT NULL,
  `freedom_order_customer_externalcode` text DEFAULT NULL,
  `freedom_order_customer_name` text DEFAULT NULL,
  `freedom_order_customer_email` text DEFAULT NULL,
  `freedom_order_customer_cpfcnpj` text DEFAULT NULL,
  `freedom_order_customer_inscricaoestadual` text DEFAULT NULL,
  `freedom_order_customer_birthdate` text DEFAULT NULL,
  `freedom_order_customer_createdate` text DEFAULT NULL,
  `freedom_order_customer_gender` text DEFAULT NULL,
  `freedom_order_customer_persontype` text DEFAULT NULL,
  `freedom_order_customer_phonenumber` text DEFAULT NULL,
  `freedom_order_customer_phoneddd` text DEFAULT NULL,
  `freedom_order_customer_mobilenumber` text DEFAULT NULL,
  `freedom_order_customer_mobileddd` text DEFAULT NULL,
  `freedom_order_customer_score` text DEFAULT NULL,
  `freedom_order_customer_address_country` text DEFAULT NULL,
  `freedom_order_customer_address_state` text DEFAULT NULL,
  `freedom_order_customer_address_statecode` text DEFAULT NULL,
  `freedom_order_customer_address_city` text DEFAULT NULL,
  `freedom_order_customer_address_street` text DEFAULT NULL,
  `freedom_order_customer_address_number` text DEFAULT NULL,
  `freedom_order_customer_address_district` text DEFAULT NULL,
  `freedom_order_customer_address_postalcode` text DEFAULT NULL,
  `freedom_order_customer_address_referencepoint` text DEFAULT NULL,
  `freedom_order_customer_address_description` text DEFAULT NULL,
  `freedom_order_customer_address_businessaddress` text DEFAULT NULL,
  `freedom_order_payments_cardholder` text DEFAULT NULL,
  `freedom_order_payments_expirationmonth` text DEFAULT NULL,
  `freedom_order_payments_expirationyear` text DEFAULT NULL,
  `freedom_order_payments_securitycode` text DEFAULT NULL,
  `freedom_order_payments_cardbrand` text DEFAULT NULL,
  `freedom_order_payments_installmentsnumber` text DEFAULT NULL,
  `freedom_order_payments_value` text DEFAULT NULL,
  `freedom_order_payments_optin` text DEFAULT NULL,
  `freedom_order_payments_externalcode` text DEFAULT NULL,
  `freedom_order_payments_paymentdate` text DEFAULT NULL,
  `freedom_order_payments_deliveryid` text DEFAULT NULL,
  `freedom_order_payments_typepayment` text DEFAULT NULL,
  `freedom_order_shippings_deliveryid` text DEFAULT NULL,
  `freedom_order_shippings_servicedelivery` text DEFAULT NULL,
  `freedom_order_shippings_deadlineindays` text DEFAULT NULL,
  `freedom_order_shippings_expecteddeliverydate` text DEFAULT NULL,
  `freedom_order_shippings_freight` text DEFAULT NULL,
  `freedom_order_shippings_canceledpayment` text DEFAULT NULL,
  `freedom_order_shippings_status` text DEFAULT NULL,
  `freedom_order_shippings_laststatusdate` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_date` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_username` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_statushistory_status` text DEFAULT NULL,
  `freedom_order_shippings_address_country` text DEFAULT NULL,
  `freedom_order_shippings_address_state` text DEFAULT NULL,
  `freedom_order_shippings_address_statecode` text DEFAULT NULL,
  `freedom_order_shippings_address_city` text DEFAULT NULL,
  `freedom_order_shippings_address_street` text DEFAULT NULL,
  `freedom_order_shippings_address_number` text DEFAULT NULL,
  `freedom_order_shippings_address_district` text DEFAULT NULL,
  `freedom_order_shippings_address_postalcode` text DEFAULT NULL,
  `freedom_order_shippings_address_referencepoint` text DEFAULT NULL,
  `freedom_order_shippings_address_description` text DEFAULT NULL,
  `freedom_order_shippings_address_businessaddress` text DEFAULT NULL,
  `freedom_order_shippings_recipient_name` text DEFAULT NULL,
  `freedom_order_shippings_recipient_cpfcnpj` text DEFAULT NULL,
  `freedom_order_shippings_recipient_birthdate` text DEFAULT NULL,
  `freedom_order_shippings_recipient_gender` text DEFAULT NULL,
  `freedom_order_shippings_recipient_persontype` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phonenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_phoneddd` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobilenumber` text DEFAULT NULL,
  `freedom_order_shippings_recipient_mobileddd` text DEFAULT NULL,
  `freedom_order_shippings_products_externalcode` text DEFAULT NULL,
  `freedom_order_shippings_products_sku` text DEFAULT NULL,
  `freedom_order_shippings_products_unitprice` text DEFAULT NULL,
  `freedom_order_shippings_products_unitdiscount` text DEFAULT NULL,
  `freedom_order_shippings_products_quantity` text DEFAULT NULL,
  `freedom_order_shippings_products_productname` text DEFAULT NULL,
  `freedom_order_shippings_products_freebie` text DEFAULT NULL,
  `freedom_order_shippings_products_netprice` text DEFAULT NULL,
  `freedom_order_shippings_carrier_id` text DEFAULT NULL,
  `freedom_order_shippings_carrier_tradingname` text DEFAULT NULL,
  `freedom_order_timestamp` text DEFAULT NULL,
  `freedom_order_shippings_sellerid` text DEFAULT NULL,
  `freedom_order_shippings_agreedate` text DEFAULT NULL,
  `freedom_order_device` text DEFAULT NULL,
  `freedom_order_utm_key` text DEFAULT NULL,
  `freedom_order_utm_value` text DEFAULT NULL,
  `freedom_order_unique_id` text DEFAULT NULL,
  `freedom_order_utm_key_id` text DEFAULT NULL,
  `freedom_order_date_publish_kafka` text DEFAULT NULL,
  `freedom_order_nm_country` text DEFAULT NULL,
  `freedom_order_date_load` text DEFAULT NULL,
  `freedom_order_hour_load` text DEFAULT NULL,
  `freedom_order_minute_load` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

select * from ods3.totalpedidos;

select * from ods3.de_para;

SELECT DISTINCT a.freedom_order_sr_sku,  b.shippings_products_productname 
FROM ods3.totalpedidos as a 
LEFT JOIN ods3.de_para as b 
ON b.sr_sku = a.freedom_order_sr_sku
group by a.freedom_order_sr_sku,  b.shippings_products_productname;

ORDER BY b.shippings_products_productname;

SELECT * FROM ODS3.TOTALPEDIDOS;

Deduplica | Retorna status do pedido por hora
 
 SELECT b.freedom_order_sr_sku,
       a.freedom_order_sr_order,
       a.status_timestamp,
       b.freedom_order_shippings_products_productname,
       b.freedom_order_shippings_products_sku,
       b.freedom_order_shippings_products_unitprice,
       b.freedom_order_shippings_products_unitdiscount,
     b.freedom_order_shippings_products_quantity,
       b.freedom_order_shippings_products_netprice
FROM ods3.totalpedidos as b,
    ( SELECT DISTINCT
       freedom_order_sr_order, 
       SUBSTR(freedom_order_shippings_statushistory_date,1,13) as status_timestamp
         FROM ods3.totalpedidos
       ORDER BY freedom_order_sr_order, status_timestamp desc) as a
       WHERE  a.freedom_order_sr_order = b.freedom_order_sr_order;

Create table stage1.dimensao ( 
`freedom_order_sr_sku` text DEFAULT NULL,
`freedom_order_shippings_products_productname` text DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO  stage1.dimensao 
SELECT freedom_order.sr_sku, freedom_order_shippings_products_productname
FROM ods3.totalpedidos;

select * from  stage1.dimensao;
select * from ods3.totalpedidos;

CREATE TABLE stage1.ft_pedidos (
    freedom_order_sr_order VARCHAR(30) NOT NULL,
    freedom_order_customer_cpfcnpj VARCHAR(20) NOT NULL,
    freedom_order_sr_sku VARCHAR(20) NOT NULL,
    status_date DATE NOT NULL,
    status_hour INT NOT NULL,
    freedom_order_shippings_products_unitprice DOUBLE NOT NULL,
    freedom_order_shippings_products_unitdiscount DOUBLE NOT NULL,
    freedom_order_shippings_products_quantity INT NOT NULL,
    freedom_order_shippings_products_netprice DOUBLE NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

drop table stage1.ft_pedidos;

select * from  stage1.ft_pedidos;

INSERT INTO  stage1.ft_pedidos 
SELECT freedom_order.sr_order, freedom_order.sr_sku, freedom_order_shippings_products_sku, freedom_order_shippings_products_unitprice, freedom_order_shippings_products_unitdiscount, freedom_order_shippings_products_quantity, freedom_order_shippings_products_netprice
FROM ods3.totalpedidos

create database dw2;

use dw2;
CREATE TABLE dw2.dim_product (
    freedom_order_sr_sku VARCHAR(20) NOT NULL,
    freedom_order_shippings_products_productname TEXT NOT NULL,
    PRIMARY KEY (freedom_order_sr_sku)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

SELECT DISTINCT
     freedom_order_sr_sku,
	 freedom_order_shippings_products_productname
	 FROM stage1.pedidos00cleansing
     ORDER BY freedom_order_shippings_products_productname;


CREATE TABLE dw2.ft_order (
    freedom_order_sr_order VARCHAR(30) NOT NULL,
    freedom_order_customer_cpfcnpj VARCHAR(20) NOT NULL,
    freedom_order_sr_sku VARCHAR(20) NOT NULL,
    status_date DATE NOT NULL,
    status_hour INT NOT NULL,
    freedom_order_shippings_products_unitprice DOUBLE NOT NULL,
    freedom_order_shippings_products_unitdiscount DOUBLE NOT NULL,
    freedom_order_shippings_products_quantity INT NOT NULL,
    freedom_order_shippings_products_netprice DOUBLE NOT NULL,
    PRIMARY KEY (freedom_order_sr_order),
    FOREIGN KEY (freedom_order_customer_cpfcnpj) REFERENCES dim_customer(freedom_order_customer_cpfcnpj),
    FOREIGN KEY (freedom_order_sr_sku) REFERENCES dim_product(freedom_order_sr_sku)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE dw2.dim_customer (
    freedom_order_customer_cpfcnpj VARCHAR(30) NOT NULL,
    freedom_order_customer_externalcode VARCHAR(15) NOT NULL,
    freedom_order_customer_name TEXT NOT NULL,
    freedom_order_customer_email TEXT NOT NULL,
    freedom_order_customer_birthdate DATE,
    freedom_order_customer_createdate TIMESTAMP,
    freedom_order_customer_gender VARCHAR(10) NOT NULL,
    freedom_order_customer_persontype VARCHAR(10) NOT NULL,
    freedom_order_customer_phonenumber VARCHAR(15) NOT NULL,
    freedom_order_customer_phoneddd VARCHAR(2) NOT NULL,
    freedom_order_customer_mobilenumber VARCHAR(15) NOT NULL,
    freedom_order_customer_mobileddd VARCHAR(2) NOT NULL,
    freedom_order_customer_score DOUBLE NOT NULL,
    freedom_order_customer_address_country VARCHAR(2) NOT NULL,
    freedom_order_customer_address_state VARCHAR(20) NOT NULL,
    freedom_order_customer_address_statecode VARCHAR(2) NOT NULL,
    freedom_order_customer_address_city VARCHAR(20) NOT NULL,
    freedom_order_customer_address_street TEXT NOT NULL,
    freedom_order_customer_address_number VARCHAR(5) NOT NULL,
    freedom_order_customer_address_district TEXT NOT NULL,
    freedom_order_customer_address_postalcode VARCHAR(10) NOT NULL,
    PRIMARY KEY (freedom_order_customer_cpfcnpj)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

##################

TRUNCATE table stage1.dimensao;
TRUNCATE table dw2.ft_order;

use ods3;
SELECT *, COALESCE(f.shippings_products_productname, o.freedom_order_shippings_products_productname) as product_name
from ods3.totalpedidos o left join de_para f on o.freedom_order_sr_sku = f.sr_sku;

# INSERIR DIMENSÃO #

INSERT INTO  stage1.dimensao ( freedom_order_sr_sku, freedom_order_shippings_products_productname) 
SELECT
f.sr_sku,
f.shippings_products_productname
from ods3.totalpedidos o 
left join de_para f 
on o.freedom_order_sr_sku = f.sr_sku;

select * from stage1.dimensao;

select count(*) from ods3.totalpedidos;
select count(*) from stage1.dimensao;

truncate table ods3.totalpedidos;
truncate table stage1.dimensao;

select * from stage1.dimensao;

#Inserir en fato_p los campos correspondientes.
INSERT INTO stage1.fato ( freedom_order_sr_order, freedom_order_sr_sku, freedom_order_shippings_products_sku, freedom_order_shippings_products_unitprice, freedom_order_shippings_products_unitdiscount, freedom_order_shippings_products_quantity, freedom_order_shippings_products_netprice) 
SELECT
o.freedom_order_sr_order, 
o.freedom_order_sr_sku, 
o.freedom_order_shippings_products_sku, 
o.freedom_order_shippings_products_unitprice, 
o.freedom_order_shippings_products_unitdiscount, 
o.freedom_order_shippings_products_quantity, 
o.freedom_order_shippings_products_netprice
from ods3.totalpedidos as o;

select * from stage1.fato;

use stage1;

# criando tabela fato #
CREATE TABLE fato (
  table_id int(10) NOT NULL AUTO_INCREMENT,
  freedom_order_sr_order text NOT NULL,
  freedom_order_sr_sku text NOT NULL,
  freedom_order_shippings_products_sku text NOT NULL,
  freedom_order_shippings_products_unitprice text NOT NULL,
  freedom_order_shippings_products_unitdiscount text NOT NULL,
  freedom_order_shippings_products_quantity text NOT NULL,
  freedom_order_shippings_products_netprice text NOT NULL,
  PRIMARY KEY (table_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

select * from stage1.fato;


